### ISSUE TITLE
Skill doesn't deploy correctly

### ISSUE THREAD

**Issue by srozga** [alexa/skill-sample-nodejs-buttons-trivia#3]
Hi there

I cloned the repo, create a trivia-skill profile and then ran `ask deploy -p trivia-skill`. Here is the output I'm getting. Using ask version 1.4.1.
```
Skill Id: amzn1.ask.skill.99132e0c-c9e3-433b-8d24-b5f7a171f410
Skill deployment finished.
Model deployment finished.
Create Lambda error.
ResourceConflictException: Function already exist: ask-custom-echo-button-trivia-skill
```

The skill is created, the function is created but the skill endpoint is not set.

Much thanks!
-s

**Comment by mdinescu** [comment]
Hi here,

I have seen this happen occasionally with the ASK CLI when there are multiple endpoints configured. The issue goes away if you redeploy.

Please run `ask deploy -p trivia-skill` one more time and update this issue either way.  If all is good, the Lambda functions should be created in your account in both NA and EU and you should see the skill endpoint information updated.

**Comment by srozga** [comment]
Fair enough that worked. I think the problem was that ask was trying to create multiple Lambda functions with the same name; one for US and another one for NA. Seems I'm good now, thanks.
