### ISSUE TITLE
Invalid json

### ISSUE THREAD

**Issue by mikevocalz** [alexa/skill-sample-nodejs-buttons-trivia#4]
Every time i run ask deploy -p trivia-skill i get the error:

Invalid json: /Users/mac/skill-sample-nodejs-buttons-trivia-master/.ask/config

**Comment by mikevocalz** [comment]
i found the error. Add a closing bracket to the end of the config file

**Comment by justinpecott** [comment]
Thanks Mike, I've committed the fix.
